### ISSUE TITLE
Update benchmark is flawed

### ISSUE THREAD

**Issue by maroux** [efectn/go-orm-benchmarks#5]
Since Insert doesn't check for created Id for raw and ent, the inserted model's id is `0` and hence the subsequence update doesn't affect any rows, and hence the code if flawed.

**Comment by efectn** [comment]
You're right. Update results are flawed. If you are free, can you send a PR? I'll be busy with other tasks for 3-4 days @maroux

**Comment by maroux** [comment]
Additionally, I don't know why `testing.B` code is duplicated here instead of just using `go test -bench` :/

**Comment by efectn** [comment]
> Additionally, I don't know why `testing.B` code is duplicated here instead of just using `go test -bench` :/

I'll change benchmark suite by `testing.Benchmark()` on next week. I have a design in my mind.
